version: "3"
services:
  stacks-node-follower:
    image: blockstack/stacks-blockchain:feat-miner-control
    volumes:
      - ./private-testnet:/src/stacks-node
    command: sh -c "sleep 60 && /bin/stacks-node start --config /src/stacks-node/Config.toml"
  explorer:
    image: blockstack/explorer:latest
    container_name: explorer
    environment:
      - NEXT_PUBLIC_MAINNET_API_SERVER=http://stacks-node-api.stacks-blockchain:3999
      - NEXT_PUBLIC_TESTNET_API_SERVER=http://stacks-node-api.stacks-blockchain:3399
      - MOCKNET_API_SERVER=http://localhost:3999
      - TESTNET_API_SERVER=http://localhost:3999
    ports:
      - 3000:3000
    networks:
      - stacks-blockchain
  bitcoin:
    image: blockstack/bitcoind:puppet-chain
    container_name: bitcoin
    restart: on-failure
    volumes:
      - ./private-testnet:/etc/bitcoin
    expose:
      - 18443
      - 28444
    environment:
      - DYNAMIC_GENESIS_TIMESTAMP=1
      - RUST_BACKTRACE=1
    networks:
      - stacks-blockchain
