services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: on-failure
    ports:
      - ${NGINX_PROXY_PORT:-80}:80
    networks:
      - default
    profiles:
      - stacks-blockchain
    volumes:
      - ${SCRIPTPATH}/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
